spring:
  application:
    name: ms-products
  datasource:
    url: ${URL_DATABASE:jdbc:mysql://localhost:3306/softwaredb}
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: ${PORT:9151}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}


key: ABCDabcd1234

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080/auth}
  autodetect-bearer-only: true
  resource: farmacia
  credentials:
    secret: GqNti8pigIbn1TSktoiFq0ptsSYKG3fc
  realm: 5to
  securityConstraints:
    - securityCollections:
        - patterns:
            - /product/*
  ssl-required: external
  use-resource-role-mappings: false